In [17]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing import image_dataset_from_directory

In [19]:
train_dir = 'C:/Users/Aziz/Desktop/Alzheimer_s Dataset/Alzheimer_s Dataset/train'  
test_dir = 'C:/Users/Aziz/Desktop/Alzheimer_s Dataset/Alzheimer_s Dataset/test'

In [21]:
# Load the dataset
train_dataset = image_dataset_from_directory(
    train_dir,
    image_size=(150, 150),  # Resize all images to this size
    batch_size=32
)


Found 5121 files belonging to 4 classes.


In [25]:
test_dataset = image_dataset_from_directory(
    test_dir,
    image_size=(150, 150),  # تغيير حجم الصور إلى 150x150 بكسل
    batch_size=32
)

Found 1279 files belonging to 4 classes.


In [27]:
# Normalize the images
normalization_layer = layers.Rescaling(1./255)
train_dataset = train_dataset.map(lambda x, y: (normalization_layer(x), y))
test_dataset = test_dataset.map(lambda x, y: (normalization_layer(x), y))


In [29]:
# Create the ANN model
model = keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Use 'softmax' for multi-class problems
])



C:\Users\Aziz\Downloads\Programs\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [31]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



In [33]:
# Train the model
model.fit(train_dataset, epochs=20, validation_data=test_dataset)


Epoch 1/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 42s 246ms/step - accuracy: 0.0106 - loss: -76232.8672 - val_accuracy: 0.0094 - val_loss: -25742720.0000
Epoch 2/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 39s 244ms/step - accuracy: 0.0097 - loss: -9095631.0000 - val_accuracy: 0.0094 - val_loss: -632681088.0000
Epoch 3/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 39s 239ms/step - accuracy: 0.0084 - loss: -111968608.0000 - val_accuracy: 0.0094 - val_loss: -3760482816.0000
Epoch 4/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 38s 232ms/step - accuracy: 0.0082 - loss: -531777600.0000 - val_accuracy: 0.0094 - val_loss: -12520996864.0000
Epoch 5/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 37s 231ms/step - accuracy: 0.0080 - loss: -1598350976.0000 - val_accuracy: 0.0094 - val_loss: -30813761536.0000
Epoch 6/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 37s 232ms/step - accuracy: 0.0083 - loss: -3716993280.0000 - val_accuracy: 0.0094 - val_loss: -63018733568.0000
Epoch 7/20
161/161 ━━━━━━━━━━━━━━━━━━━━ 38s 232ms/step - accuracy: 0.0085 - loss: -7262699008.0000 - val

In [35]:
# Evaluate the model
loss, accuracy = model.evaluate(test_dataset)
print(f'Accuracy: {accuracy:.4f}')



40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - accuracy: 0.0067 - loss: -4552462434304.0000
Accuracy: 0.0094


In [37]:
# Predictions
y_true = np.concatenate([y for x, y in test_dataset], axis=0)
y_pred = (model.predict(test_dataset) > 0.5).astype("int32").flatten()



40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step


In [41]:
# Evaluation metrics
print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))


[[  0 179   0   0]
 [  0  12   0   0]
 [  0 640   0   0]
 [  0 448   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       179
           1       0.01      1.00      0.02        12
           2       0.00      0.00      0.00       640
           3       0.00      0.00      0.00       448

    accuracy                           0.01      1279
   macro avg       0.00      0.25      0.00      1279
weighted avg       0.00      0.01      0.00      1279



C:\Users\Aziz\Downloads\Programs\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Aziz\Downloads\Programs\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Aziz\Downloads\Programs\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
