In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras import layers

In [3]:
train_dir = 'C:/Users/Aziz/Desktop/Alzheimer_s Dataset/Alzheimer_s Dataset/train'  
test_dir = 'C:/Users/Aziz/Desktop/Alzheimer_s Dataset/Alzheimer_s Dataset/test'

In [5]:
# Load training and testing images
train_dataset = image_dataset_from_directory(
    train_dir,
    image_size=(150, 150),
    batch_size=32
)

Found 5121 files belonging to 4 classes.


In [7]:
test_dataset = image_dataset_from_directory(
    test_dir,
    image_size=(150, 150),
    batch_size=32
)

Found 1279 files belonging to 4 classes.


In [9]:
# Normalize images
normalization_layer = layers.Rescaling(1./255)
train_dataset = train_dataset.map(lambda x, y: (normalization_layer(x), y))
test_dataset = test_dataset.map(lambda x, y: (normalization_layer(x), y))

In [11]:
# Convert dataset to numpy arrays
train_images = np.concatenate([x.numpy() for x, y in train_dataset], axis=0)
train_labels = np.concatenate([y.numpy() for x, y in train_dataset], axis=0)

test_images = np.concatenate([x.numpy() for x, y in test_dataset], axis=0)
test_labels = np.concatenate([y.numpy() for x, y in test_dataset], axis=0)

In [13]:
# Flatten images for KNN
train_images = train_images.reshape(train_images.shape[0], -1)
test_images = test_images.reshape(test_images.shape[0], -1)

In [15]:
# Normalize the data
scaler = StandardScaler()
train_images = scaler.fit_transform(train_images)
test_images = scaler.transform(test_images)


In [17]:
# Train KNN model
k = 5
knn_model = KNeighborsClassifier(n_neighbors=k)
knn_model.fit(train_images, train_labels)

KNeighborsClassifier()

In [19]:
# Make predictions
y_pred = knn_model.predict(test_images)

In [21]:
# Evaluate the model
print(confusion_matrix(test_labels, y_pred))
print(classification_report(test_labels, y_pred))

[[  2   0 137  40]
 [  0   0  11   1]
 [ 21   1 498 120]
 [  7   0 346  95]]
              precision    recall  f1-score   support

           0       0.07      0.01      0.02       179
           1       0.00      0.00      0.00        12
           2       0.50      0.78      0.61       640
           3       0.37      0.21      0.27       448

    accuracy                           0.47      1279
   macro avg       0.23      0.25      0.22      1279
weighted avg       0.39      0.47      0.40      1279

